config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # devise_for :users, :controllers => { registrations: 'registrations' }
  resources :jobs
  resources :boats
  resources :photos
  root to: 'boats#index'
  get "/add_boats/:job_id" => "jobs#add_boats"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :boats_jobs
    has_many :boats, through: :boats_jobs
    has_many :comments
    belongs_to :user

    validates :destination, inclusion: { in: Locations.list,
    message: "Invalid destination" }
    validates :origin, inclusion: { in: Locations.list,
    message: "Invalid origin" }
    validates :cost, numericality: { greater_than: 1000 }
    validates :description, length: {minimum: 50}

    validate :origin_different_from_destination

    def origin_different_from_destination
        if origin == destination
            errors.add(:destination, "must be different from origin")
        end
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def add_boats
      puts "\n*****add_boats****"
      puts "\n****** params.inspect, #{params.inspect} ******"
      @job = Job.find(params[:job_id])
  end

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @comment = Comment.new
    @boats = BoatsJob.where(job_id:@job.id)
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        @boatsjob = BoatsJob.new
        @boatsjob.boat_id = params["boat_ids"]
        @boatsjob.job_id = @job.id
        @boatsjob.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        # format.json { render :show, status: :created, location: @job }
        format.js
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:containers, :description, :cost, :origin, :destination, boat_ids:[])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, remote: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :origin %>
    <%= form.select(:origin, Locations.list, {:prompt => true}) %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.select(:destination, Locations.list, {:prompt => true}) %>
  </div>

  <div class="field">
    <%= form.label :boats %>
    <%= form.select :boat_ids, current_user.boats.collect {|boat| [boat.name, boat.id]}, {}, :multiple => true %>
  </div>

  <div class="field">
    <%= form.label :containers %>
    <%= form.number_field :containers, id: :job_containers %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost, id: :job_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/create.js.erb
alert("Saved")

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<h1 align="center" class="boatsh1">Jobs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Containers</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Origin</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.user_id %></td>
        <td><%= job.containers %></td>
        <td><%= job.description %></td>
        <td><%= job.cost %></td>
        <td><%= job.origin %></td>
        <td><%= job.destination %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %> <br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @job.user_id %>
</p>

<p>
  <strong>Containers:</strong>
  <%= @job.containers %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @job.cost %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @job.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @job.destination %>
</p>

<br>
<br>

<p>
  <strong>Boat ID:</strong>
  <% @boats.each do |boat| %>
  <%= boat.id %>
  <% end %>
</p>

<p>
    <strong>All Comments</strong>
    <% @job.comments.each do |comment| %>
        <%= comment.comment %> <br>
    <% end %>
</p>

<p>
  <strong>New Comment</strong>
 <%= form_with(model: @comment, url: comments_path, local:true) do |form| %>
 <% if @comment.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

     <ul>
     <% @comment.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

    <div class="field">
      <%= form.label :comment %>
      <%= form.text_area :comment %>
      <%= form.hidden_field :job_id, value: @job.id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>
<!-- <%= link_to 'Add Boat', "/add_boats/#{@job.id}", remote: true %> -->