config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # devise_for :users, :controllers => { registrations: 'registrations' }
  resources :jobs
  resources :boats
  resources :photos
  root to: 'boats#index'
  get "/add_boats/:job_id" => "jobs#add_boats"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :boat

  has_attached_file :image,       # declares that model has an attachment and provides name (:image)
      styles: {
          large: "500x500#",
          medium: "300x300#",
          thumb: "100x100#"
      },
      convert_options: {
          thumb: "-quality 75 -strip",
          original: "-quality 85 -strip"
      },
      storage: :s3,
      s3_region: ENV["S3_REGION"],
      s3_credentials: {
          bucket: ENV["S3_BUCKET"],
          access_key_id: ENV["AWS_ACCESS_KEY_ID"],
          secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
      },
      default_url: "/images/:style/missing_image.jpg"
  validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      puts "\n******* photo_params ******"
      params.require(:photo).permit(:image, :title, :content_type, :boat_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
<% if photo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

    <ul>
    <% photo.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

    <div class="field">
        <%= f.label :boat_id %><br />
        <%= f.select(:boat_id, current_user.boats.collect {|boat| [boat.name, boat.id]}) %>
    </div>
   <div class="field">
        <%= f.label :content_type %><br />
        <%= f.select(:content_type, options_for_select([['image/jpeg', 1], ['image/png', 2], ['image/gif', 3]], 1)) %>
    </div>
    <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true %>
    </div>
    <div class="file-field">
        <%= f.label :image %><br />
        <%= f.file_field :image, class: 'file-field' %>
    </div>
    <div class="field">
        <%= f.submit "Save Photo", class: 'photo-button' %>
    </div>

<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>