config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # devise_for :users, :controllers => { registrations: 'registrations' }
  resources :jobs
  resources :boats
  resources :photos
  root to: 'boats#index'
  get "/add_boats/:job_id" => "jobs#add_boats"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boat.rb
class Boat < ApplicationRecord
    has_many :boats_jobs
    has_many :jobs, through: :boats_jobs
    has_many :photos
    belongs_to :user

    validates :name, uniqueness: { case_sensitive: false }
    validates :location, inclusion: { in: Locations.list,
    message: "Invalid location" }

    accepts_nested_attributes_for :boats_jobs
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = current_user.boats
    puts " ** ENV['S3_REGION']: #{ENV['S3_REGION'].inspect}"
    puts " ** ENV['S3_BUCKET']: #{ENV['S3_BUCKET'].inspect}"
    puts " ** ENV['AWS_ACCESS_KEY_ID']: #{ENV['AWS_ACCESS_KEY_ID'].inspect}"
    puts " ** ENV['AWS_SECRET_ACCESS_KEY']: #{ENV['AWS_SECRET_ACCESS_KEY'].inspect}"
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)
    @boat.user_id = current_user.id

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        # format.json { render :show, status: :created, location: @boat }
        format.js
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :containers, :location)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_with(model: boat, remote: true) do |form| %>
  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :boat_name %>
  </div>

  <div class="field">
    <%= form.label :containers %>
    <%= form.number_field :containers, id: :boat_containers %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.select(:location, Locations.list, {:prompt => true}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boats/create.js.erb
alert("Saved")

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>

<h1 align="center" class="boatsh1">Boats</h1>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Containers</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        <td><%= boat.containers %></td>
        <td><%= boat.location %></td>
        <td><%= link_to 'Show', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %> <br>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>


    <% if @boat.photos.first %>
<p>
    <%= image_tag @boat.photos.first.image.url(:medium) %>
</p>
    <% end %>

<p>
  <strong>User:</strong>
  <%= @boat.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @boat.name %>
</p>

<p>
  <strong>Containers:</strong>
  <%= @boat.containers %>
</p>

<p>
  <strong>Location:</strong>
  <%= @boat.location %>
</p>

<p>
  <strong>Jobs:</strong>
  <% @boat.jobs.each do |job| %>
    <%= job.origin + " ---> " + job.destination %> <br>
  <% end %>
</p>

<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>